### ISSUE TITLE
 I can't reproduce the results reported in the paper

### ISSUE THREAD

**Issue by superwars** [tmliang/SeG#1]
Based on your code, I can't reproduce the results reported in the paper, and the results are also different from your Experimental Result, which is auc:0.452, P@100:0.810, P@200:0.790, P@300:0.763, Mean:0.772. My result is auc:0.415 , P@100:0.770, P@200:0.795, P@300:0.733, Mean:0.766.
By the way, your code doesn't seem to run directly. I modified a few lines of code about model saving and loading.

**Comment by tmliang** [comment]
Sorry for not checking the code carefully before uploading, and I have made two changes,
1. fixing the bugs of model saving and loading, and the code can be run directly now;
2. according to the source code of [CoRA](https://github.com/YangLi1221/CoRA) (another work of the same authors), the entity-aware embeddings should be **divided** by lambda **instead of multiplication**.

And now you may reproduce my results, although still far from that reported on the paper.

**Comment by superwars** [comment]
Thanks!
